### ISSUE TITLE
bug: java.lang.ClassCastException: etaoin.api$get_logs cannot be cast to clojure.lang.MultiFn

### ISSUE THREAD

**Issue by borkdude** [igrishaev/etaoin#212]
The interesting part of the stacktrace:

```
[08:05:53]    Uncaught exception, not in assertion.
[08:05:53]    expected: nil
[08:05:53]    actual: java.lang.ClassCastException: etaoin.api$get_logs cannot be cast to clojure.lang.MultiFn
[08:05:53]    at clojure.core$get_method.invokeStatic (core.clj:1817)
[08:05:53]    clojure.core$get_method.invoke (core.clj:1817)
[08:05:53]    etaoin.api$implemented_QMARK_.invokeStatic (api.clj:71)
[08:05:53]    etaoin.api$implemented_QMARK_.invoke (api.clj:69)
[08:05:53]    etaoin.api$supports_logs_QMARK_.invokeStatic (api.clj:1498)
[08:05:53]    etaoin.api$supports_logs_QMARK_.invoke (api.clj:1495)
[08:05:53]    etaoin.api$postmortem_handler.invokeStatic (api.clj:2522)
[08:05:53]    etaoin.api$postmortem_handler.invoke (api.clj:2491)
```

It seems get-logs is no longer a multimethod.

**Comment by luontola** [comment]
An unofficial build with @borkdude's fix is available at `[org.clojars.luontola/etaoin "0.3.5-patch1"]`

**Comment by CamdenClark** [comment]
> An unofficial build with @borkdude's fix is available at `[org.clojars.luontola/etaoin "0.3.5-patch1"]`

@luontola If you're ever in seattle, I owe you a drink. Thanks so much!

**Comment by igrishaev** [comment]
Sorry for the delay, Alex and I just got back to the library. Yes, the `get-logs` if now a function which relies on the internal `get-logs*` multimethod. Is anyone still facing troubles with that? If so, could you provide some code/examples, please?

**Comment by borkdude** [comment]
I believe this was fixed by this PR: https://github.com/igrishaev/etaoin/pull/213

**Comment by igrishaev** [comment]
Right, thanks!
